ungdev/EtuUTT

src/Etu/Core/ApiBundle/Oauth/GrantType/RefreshTokenGrantType.php

FIX #18 Introduce refresh token in the response

---

src/Etu/Module/DaymailBundle/Entity/DaymailPart.php

Update edition time limit for the DayMail up to 6AM.

Daymail change

---

src/Etu/Core/ApiBundle/Controller/SecurityController.php
src/Etu/Core/ApiBundle/Listener/SecurityListener.php
web/.htaccess

\o/ Hooray.
- Add Authorization header when using Apache
- Add support for Bearer :+1:
- Pass code (and authorization_code) everywhere … (in two places)

🍆 Finish OAuth2 compatibility ! Yay

---

composer.json
src/Etu/Core/CoreBundle/Framework/Definition/Controller.php
src/Etu/Module/EventsBundle/Controller/MembershipsController.php
web/src/js/bundles/events.js
web/src/js/bundles/events_public.js

This group of fix make the event module work.
I had to update the ` composer.json` file but I cannot push the `composer.lock` because my system is not compatible with one of the package (because php7). I had to remove the package to check if my fix work. So someone will have to do `composer update` on a clean install with all packages.

Fix event module

---

src/Etu/Module/DaymailBundle/BodyParser/BodyParser.php
src/Etu/Module/DaymailBundle/Resources/views/Memberships/daymail.html.twig

These modifications should fix daymail image insertion on slow connections.

Fix daymail image insertion

---

src/Etu/Module/DaymailBundle/Resources/views/Memberships/daymail.html.twig

Fix daymail js script compatibility with IE and chrome

Fix js script compatibility with IE and chrome

---

src/Etu/Module/DaymailBundle/Resources/views/Mail/daymail.html.twig

Track daymail opening

---

src/Etu/Core/UserBundle/Api/QueryMapper/UserListMapper.php
src/Etu/Core/UserBundle/Api/Resource/PublicUsersListController.php

Recherche d'utilisateur par leur n°etu. _Per_ Grégoire Martron.

Filtres users

---

src/Etu/Module/WikiBundle/Controller/MainController.php
src/Etu/Module/WikiBundle/Entity/WikiPage.php
src/Etu/Module/WikiBundle/Resources/translations/messages.fr.yml
src/Etu/Module/WikiBundle/Resources/views/Main/delete.html.twig
src/Etu/Module/WikiBundle/Resources/views/Main/move.html.twig
src/Etu/Module/WikiBundle/Resources/views/Main/part_headbar.html.twig
src/Etu/Module/WikiBundle/Resources/views/Main/view.html.twig
src/Etu/Module/WikiBundle/Services/PermissionsChecker.php

* Il y avait un problème au niveau de l'index des wiki, il classait les pages dans le mauvais ordre :
```
nom
nom-test
nom/page-fille
nom
nom/page-fille
nom-test
```
* L'editeur peut proposer des liens du wiki directement, mais ça ne fonctionnait pas dans le wiki general. Maintenant oui.
* Ajout de pages permettant de supprimer ou de déplacer des pages de wiki.

Some wiki enhancements

---

src/Etu/Core/UserBundle/Api/QueryMapper/UserListMapper.php
src/Etu/Core/UserBundle/Api/Resource/PublicUsersListController.php
src/Etu/Core/UserBundle/Api/Transformer/UserTransformer.php
src/Etu/Core/UserBundle/Resources/config/services.yml

* Add possibility to filter users without using a specific field which is more natural to implement user search for client applications.
*  add `name` filter which was implemented but not documented
* Fix a notice on api reference page

Add a multifield search on user api

---

src/Etu/Module/ArgentiqueBundle/Controller/MainController.php

Extensions in Argentique gallery

---

src/Etu/Module/DaymailBundle/Entity/DaymailPart.php

Increase Daymail title length

---

.gitignore
composer.json
composer.lock
src/Etu/Core/UserBundle/Command/SendNewcomersMailCommand.php
src/Etu/Core/UserBundle/Resources/views/Mail/newcomer_mail.html.twig
var/SymfonyRequirements.php
web/config.php

Added a command to send a mail to new comers

---

src/Etu/Core/UserBundle/Resources/translations/messages.fr.yml
src/Etu/Module/UVBundle/Resources/translations/messages.fr.yml

Modification dans les traductions de "UV" en "UE". Par contre pour ne rien casser je ne me suis pas amusé à tout renommer de uv à ue dans le code.

Changement de "UV" en "UE"

---

app/Resources/translations/messages.fr.yml
src/Etu/Core/CoreBundle/Resources/views/Main/index_blocks/courses.html.twig
src/Etu/Module/UVBundle/EtuModuleUVBundle.php

Should we also change routes from "/uvs" to something like "/ue"?

[UE/UV] Even more changes from "UV" to "UE"

---

src/Etu/Core/CoreBundle/Resources/views/Main/index.html.twig

This reverts commit f03cbadcdb018a2bdc4db6fb4f753625658997ab.

Revert "added message on home page"

---

.gitignore
app/config/config.yml
app/config/modules.yml.dist
app/config/parameters.yml.dist
app/config/security.yml
composer.json
composer.lock
src/Etu/Core/UserBundle/Resources/translations/messages.fr.yml
src/Etu/Module/SIABundle/Controller/DefaultController.php
src/Etu/Module/SIABundle/DependencyInjection/Configuration.php
src/Etu/Module/SIABundle/DependencyInjection/EtuModuleSIAExtension.php
src/Etu/Module/SIABundle/EtuModuleSIABundle.php
src/Etu/Module/SIABundle/Form/createAccount.php
src/Etu/Module/SIABundle/Form/editAccount.php
src/Etu/Module/SIABundle/Ldap/LdapManager.php
src/Etu/Module/SIABundle/Ldap/Model/User.php
src/Etu/Module/SIABundle/Resources/config/services.yml
src/Etu/Module/SIABundle/Resources/translations/messages.fr.yml
src/Etu/Module/SIABundle/Resources/views/Default/index.html.twig
src/Etu/Module/SIABundle/Resources/views/Main/create.html.twig
src/Etu/Module/SIABundle/Resources/views/Main/edit.html.twig
src/Etu/Module/SIABundle/Resources/views/Main/index.html.twig

- Création de compte sur le SIA
- Reset password

EtuSIA: Création & reset

---

app/config/services.yml
src/Etu/Core/UserBundle/Command/OrganizationGroupMigrationCommand.php
src/Etu/Core/UserBundle/Controller/AdminController.php
src/Etu/Core/UserBundle/Controller/OrgaController.php
src/Etu/Core/UserBundle/Entity/Member.php
src/Etu/Core/UserBundle/Entity/Organization.php
src/Etu/Core/UserBundle/Entity/OrganizationGroup.php
src/Etu/Core/UserBundle/Entity/OrganizationGroupAction.php
src/Etu/Core/UserBundle/EventListener/MailistSubscription.php
src/Etu/Core/UserBundle/Resources/config/services.yml
src/Etu/Core/UserBundle/Resources/translations/messages.fr.yml
src/Etu/Core/UserBundle/Resources/views/Orga/groupEdit.html.twig
src/Etu/Core/UserBundle/Resources/views/Orga/memberEdit.html.twig
src/Etu/Core/UserBundle/Resources/views/Orga/members.html.twig
src/Etu/Module/AssosBundle/Controller/MainController.php
src/Etu/Module/AssosBundle/Resources/views/Main/members.html.twig
src/Etu/Module/SIABundle/Command/SyncCommand.php
src/Etu/Module/SIABundle/Ldap/LdapManager.php

NEW:
- Organization group (commission etc ...)
- Organisation group actions (mailist subcription)
- EtuSIA Organization group sync
CAUTION:
- Doctrine schema update have to run
- Membership migration command have to run too (create default group + affect member to group)

Refactor of organization membership.

---

composer.json
composer.lock
src/Etu/Module/EventsBundle/Controller/MainController.php

- Ajout du nom de l'asso dans le titre de l'event
- Fix, url de l'event en absolue.

- Description des evenements en text

---

src/Etu/Module/UVBundle/Resources/views/View/courses.html.twig

Hotfix: Schedule days fix

---

src/Etu/Core/UserBundle/Entity/User.php
src/Etu/Module/TrombiBundle/Controller/MainController.php
src/Etu/Module/TrombiBundle/Resources/views/Main/index.html.twig
web/assets/js/common.js

* Fix #76, fix #40 
* Je vais au delà des masters, j'ai ajouté en plus des masters : les doctorants, les licences pro, les mastères spécialisés, les étudiants étrangers en convention, les diplômes d'université de l'UTT
*  Résolution du bug qui faisait qu'une recherche ne donnant qu'une page lancée depuis la page deux d'une précédente recherche donnait un résultat vide (fix : toujours rediriger sur la première page lors d'une nouvelle recherche)
* Distinction des branches (toutes les spécialités ingé, master, ...) des filières de chaque branche pour encore plus de combinaisons. J'ai saisi toutes les combinaisons possibles (même celles qui ne sont plus utilisées aujourd'hui marquées par `*`), en tapant directement sur la base du site etu lors de mes recherches `SELECT DISTINCT …

Amélioration du trombi

---

src/Etu/Core/UserBundle/Api/Resource/PublicOrgasListController.php

Hello c'est le discord asso 👋 
J'aimerais bien utiliser cette route mais elle est cassée :/

fix: make route `/public/orgas/{login}/members` work
